spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: 192.168.1.81:9092
      bindings:
        cts-test-in:
          destination: cts-test
          contentType: application/json
        cts-test-out:
          destination: cts-test
          contentType: application/json
